### ISSUE TITLE
Once I have GetMatrixRuns(), how can I get the test results within?

### ISSUE THREAD

**Issue by eanxgeek** [bndr/gojenkins#17]
This may be a question the further shows how new I am to Go; however, I have tried a number of things and have not been able to access the contents of GetMatrixRuns()

```
               matrixRuns, err := build.GetMatrixRuns()

		if err != nil {
			fmt.Println(buildID.Number, " ", err)
			continue
		}
		for _, run := range matrixRuns {
				fmt.Println(i)
		}
```

Will return:
> &{0xc820204600 0xc8200e9a00 0xc82000b050  1}
> &{0xc820204d80 0xc8200e9a00 0xc82000b050  1}
> &{0xc820204f00 0xc8200e9a00 0xc82000b050  1}

I have tried to treat these as builds; however, references like run.Number do not work.

Any example or suggestions on how best to access the contents?

**Comment by bndr** [comment]
First of all I would suggest getting IDE that supports Golang autocompletion. Then you can see all the properties that are available on every object.

For matrix runs something like this should work.

```
for _, run := range matrixRuns {

			testResult, err := run.GetResultSet()

			if err != nil {
				panic(err)
			}
			if testResult != nil {
				fmt.Println(buildID.Number, " Pass count : ", testResult.PassCount, " Fail count : ", testResult.FailCount)
			}
		}
```

**Comment by eanxgeek** [comment]
So I have gotten further, but I'm not getting the data I expected.  I may asking or looking at the wrong function for what I am after.

the url is: dtests-jamq-621-r1-clients-101-downstream-acceptance-tests-r7x/HW_TYPE=kvm,JVM_TYPE=ibm_1.7.1

Which translates into, from the WebUI, job == dtests-jamq-621-r1-clients-101-downstream-acceptance-tests-r7x and configuration == HW_TYPE=kvm,JVM_TYPE=ibm_1.7.1.  Under configuration there are builds, under the configuration/build there are test results.  The final url follows:
dtests-jamq-621-r1-clients-101-downstream-acceptance-tests-r7x/HW_TYPE=kvm,JVM_TYPE=openjdk_1.7.0,labels=tcn/11/testReport/(root)/

I haven't found a way into these tests, GetMatrixRuns() gets me 0s across the board, likewise GetResultSet() gets me 0s.  I should be seeing 200 tests run 14 failed, remaining passed from the above url.

**Comment by bndr** [comment]
Hm... I'll take a look into it this evening.

**Comment by bndr** [comment]
I pushed some changes, would you mind checking if your code works now?

**Comment by eanxgeek** [comment]
Wasn't sure which approach to try to I tried with MatrixRuns using the following:
```
		matrixRuns, err := build.GetMatrixRuns()
		
		if err != nil {
			fmt.Println(buildID.Number, " ", err)
			continue
		}
		for _, run := range matrixRuns {
			matrixResultSets, err := run.GetResultSet()
			if err != nil {
				fmt.Println(err)
				continue
			} 
			fmt.Println(matrixResultSets.PassCount, " ", matrixResultSets.FailCount)
		}
```
Going this route I got absolutely nothing in STDOUT.  I got no err messages or *Count values.

> $ ./getjenkinsstats -url=http://localhost:8080 -job=job
> $

**Comment by eanxgeek** [comment]
So I tried again with the latest gojenkins code and I see no change using the following code

```
		matrixRuns, err := build.GetMatrixRuns()
		
		if err != nil {
			fmt.Println(buildID.Number, " ", err)
			continue
		}
		for _, run := range matrixRuns {
			matrixResultSets, err := run.GetResultSet()
			if err != nil {
				fmt.Println(err)
				continue
			} 
			fmt.Println("Pass Count : ", matrixResultSets.PassCount, 
						" Fail Count : ", matrixResultSets.FailCount)
		}
```

> $ ./getjenkinsstats -url=http://localhost:8080/ -job="dtests-jamq-621-r1-clients-101-downstream-acceptance-tests-r7x"
> Compiling job :  13
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Compiling job :  12
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Compiling job :  11
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
> Pass Count :  0  Fail Count :  0
>

**Comment by bndr** [comment]
Well that's strange, Perhaps it's your plugins?
Here's a working example with matrix runs

```
func main() {
	jenkins := gojenkins.CreateJenkins("https://jenkins.mono-project.com")
	_, err := jenkins.Init()
	if err != nil {
		panic(err)
	}
	job, err := jenkins.GetJob("test-mono-mainline")
	if err != nil {
		panic(err)
	}
	builds, err := job.GetAllBuildIds()
	if err != nil {
		panic(err)
	}
	for _, buildID := range builds {
		build, _ := jenkins.GetBuild("test-mono-mainline", buildID.Number)
		matrixRuns, err := build.GetMatrixRuns()
		if err != nil {
			panic(err)
		}
		for _, run := range matrixRuns {
			testResult, err := run.GetResultSet()
			if err != nil {
				panic(err)
			}
			if testResult != nil {
				fmt.Println(run.GetBuildNumber(), " Pass count : ", testResult.PassCount, " Fail count : ", testResult.FailCount)
			}
		}

	}

}
```

**Comment by eanxgeek** [comment]
This is the url for mine and a screen shot:
> http://localhost:8080/job/dtests-jamq-621-r1-clients-101-downstream-acceptance-tests-r7x/HW_TYPE=kvm,JVM_TYPE=openjdk_1.7.0,labels=tcn/11/

Not sure if these will help, I'll compare the code you have that works to mine.

![screenshot from 2016-02-25 10-38-16](https://cloud.githubusercontent.com/assets/1113174/13324471/e993f8b6-dbab-11e5-9207-812627a7471c.png)
![screenshot from 2016-02-25 10-37-46](https://cloud.githubusercontent.com/assets/1113174/13324473/ecab98a6-dbab-11e5-9969-d08fd29452b3.png)

**Comment by eanxgeek** [comment]
I do see a reference difference, I'm changing now to see if that affects things.

**Comment by eanxgeek** [comment]
My code looks nearly identical to your's, only the variables are different.

**Comment by bndr** [comment]
Can you go to your Test Results Page, click the URL at the bottom that says "REST API", and on the next page click the "JSON API" and tell me what URL is being generated?

**Comment by eanxgeek** [comment]
Without (root) expanded:
/job/dtests-jamq-621-r1-clients-101-downstream-acceptance-tests-r7x/HW_TYPE=kvm,JVM_TYPE=ibm_1.7.1,labels=tcn/11/testReport/api/json?pretty=true

with (root) expanded:
/job/dtests-jamq-621-r1-clients-101-downstream-acceptance-tests-r7x/HW_TYPE=kvm,JVM_TYPE=ibm_1.7.1,labels=tcn/11/testReport/(root)/api/json?pretty=true

What I notice in the json that is returned, at the bottom (after all 200 of the test names is final summary for failCount, passCount, etc...

>     {
>       "testActions" : [
>         
>       ],
>       "name" : "DSDynamic/SupportTests/test_nodes_set_default_jvm"
>     }
>   ],
>   "failCount" : 14,
>   "name" : "(root)",
>   "passCount" : 186,
>   "skipCount" : 0
> }

**Comment by bndr** [comment]
I updated the code once again, can you check if it helped?

**Comment by eanxgeek** [comment]
No change noted, but I am also noticing that I am not getting a build number from the following call.
```
run.GetBuildNumber()
```

Results still show:

> Compiling job :  11
> 0 Pass Count :  0  Fail Count :  0
> 0 Pass Count :  0  Fail Count :  0
> 0 Pass Count :  0  Fail Count :  0
> 0 Pass Count :  0  Fail Count :  0
> 0 Pass Count :  0  Fail Count :  0
> 0 Pass Count :  0  Fail Count :  0

**Comment by bndr** [comment]
Well this is quite strange indeed.

Here is the Jenkins CI that I tested: https://amplab.cs.berkeley.edu/jenkins/job/ADAM/1546

As you can see it also uses matrix configuration with custom parameters (Like your HW_TYPE=kvm,JVM_TYPE=ibm_1.7.1)

Here's the code that works:
```
func main() {
	jenkins := gojenkins.CreateJenkins("https://amplab.cs.berkeley.edu/jenkins")
	_, err := jenkins.Init()

	if err != nil {
		panic(err)
	}

	job, err := jenkins.GetJob("ADAM")

	if err != nil {
		panic(err)
	}

	builds, err := job.GetAllBuildIds()

	if err != nil {
		panic(err)
	}

	for _, buildID := range builds {
		build, _ := job.GetBuild(buildID.Number)

		matrixRuns, err := build.GetMatrixRuns()
		if err != nil {
			panic(err)
		}

		for _, run := range matrixRuns {

			testResult, err := run.GetResultSet()

			if err != nil {
				panic(err)
			}
			if testResult != nil {
				fmt.Println(run.GetBuildNumber(), " Pass count : ", testResult.PassCount, " Fail count : ", testResult.FailCount)
			}
		}

	}

}
```

**Comment by eanxgeek** [comment]
This code works for me, going down to the Suites/Cases.

```
		for _, run := range matrixRuns {
			matrixResultSet, err := run.GetResultSet()
			if err != nil {
				panic(err)
			}
			
			for _, suite := range matrixResultSet.Suites {
				fmt.Printf("%#v", suite)
				for _, c := range suite.Cases {
					fmt.Printf("%#v", c)
				}
			}
			
			//if matrixResultSet != nil {
			//	fmt.Println(run.GetBuildNumber(), "Pass Count : ", matrixResultSet.PassCount, 
			//			" Fail Count : ", matrixResultSet.FailCount)
			//}
		}
```

**Comment by eanxgeek** [comment]
It's all working now, it appears.

```
		for _, run := range matrixRuns {
			matrixResultSet, err := run.GetResultSet()
			if err != nil {
				panic(err)
			}
			runBuildNumber := run.GetBuildNumber()
			for _, suite := range matrixResultSet.Suites {
				fmt.Printf("\n*** %d : %s ***\n", runBuildNumber, suite.Name)
				fmt.Println("Fail Count : ", matrixResultSet.FailCount)
				for _, c := range suite.Cases {
					fmt.Printf("\n\n%#v\n\n", c)
				}
			}
			
			//if matrixResultSet != nil {
			//	fmt.Println(run.GetBuildNumber(), "Pass Count : ", matrixResultSet.PassCount, 
			//			" Fail Count : ", matrixResultSet.FailCount)
			//}
		}
```

root cause analysis would probably reveal that my python experience kicked in and I forgot to rebuild my binary after I updated the gojenkins library.

And the fixes you put in today appear to fix an issue I hit last night trying to get Suites and Cases out of a ResultSet.

Thanks!

**Comment by bndr** [comment]
Good to know it works!

**Comment by eanxgeek** [comment]
btw I think I have settled on LiteIDE.
