### ISSUE TITLE
Creating Job 403: no valid crumb provided (Jenkins with CSRF protection)

### ISSUE THREAD

**Issue by dobegor** [bndr/gojenkins#32]
Upon calling CreateJob I am getting 403 error, Jenkins log says: No valid crumb was included in request for /createItem. Returning 403.

What's wrong?

**Comment by dobegor** [comment]
The issue is caused by CSRF protection enabled.

**Comment by dcu** [comment]
@dobegor I fixed this issue, can you check?

**Comment by oneinstack** [comment]
jenkins.BuildJob the same problem

**Comment by evscott** [comment]
I'm still experiencing this issue with many commands. Does anyone know of a work around?

**Comment by slient2010** [comment]
I have met this issue, too. Any solutions?

**Comment by brainexe** [comment]
I still had the same issue... #186 is fixing it by setting the correct cookies
